<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.2</version>
		<relativePath />
	</parent>
	<properties>
		<revision>1.0.0-SNAPSHOT</revision>
		<java.version>21</java.version>
		<application-context-util.version>1.0.0-SNAPSHOT</application-context-util.version>
		<commons-lang3.version>3.13.0</commons-lang3.version>
		<commons-collections4.version>4.4</commons-collections4.version>
		<commons-math3.version>3.6.1</commons-math3.version>
		<tablesaw.version>0.43.1</tablesaw.version>
	</properties>
	<groupId>spp</groupId>
	<artifactId>spp-portfolio-manager</artifactId>
	<version>${revision}</version>
	<packaging>pom</packaging>
	<modules>
		<module>spp-portfolio-manager-utilities</module>
		<module>spp-portfolio-model</module>
		<module>spp-portfolio-configuration-manager</module>
		<module>spp-portfolio-constituents-manager</module>
		<module>spp-portfolio-manager-rest-server</module>
	</modules>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>spp</groupId>
				<artifactId>spp-portfolio-model</artifactId>
				<version>${revision}</version>
			</dependency>
			<dependency>
				<groupId>spp</groupId>
				<artifactId>spp-portfolio-manager-utilities</artifactId>
				<version>${revision}</version>
			</dependency>
			<dependency>
				<groupId>spp</groupId>
				<artifactId>spp-portfolio-configuration-manager</artifactId>
				<version>${revision}</version>
			</dependency>
			<dependency>
				<groupId>spp</groupId>
				<artifactId>spp-portfolio-constituents-manager</artifactId>
				<version>${revision}</version>
			</dependency>
			<dependency>
				<groupId>org.springdoc</groupId>
				<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
				<version>2.3.0</version>
			</dependency>
			<dependency>
				<groupId>io.github.funofprograming</groupId>
				<artifactId>application-context-util</artifactId>
				<version>${application-context-util.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-lang3</artifactId>
				<version>${commons-lang3.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-collections4</artifactId>
				<version>${commons-collections4.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-math3</artifactId>
				<version>${commons-math3.version}</version>
			</dependency>
			<dependency>
			    <groupId>tech.tablesaw</groupId>
			    <artifactId>tablesaw-core</artifactId>
			    <version>${tablesaw.version}</version>
			</dependency>
			<dependency>
			    <groupId>tech.tablesaw</groupId>
			    <artifactId>tablesaw-json</artifactId>
			    <version>${tablesaw.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-collections4</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-math3</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j2</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-spring-boot</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-context</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-json</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>io.github.funofprograming</groupId>
			<artifactId>application-context-util</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
		    <groupId>tech.tablesaw</groupId>
		    <artifactId>tablesaw-core</artifactId>
		</dependency>
		<dependency>
		    <groupId>tech.tablesaw</groupId>
		    <artifactId>tablesaw-json</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

</project>